### ISSUE TITLE
not downloading

### ISSUE THREAD

**Issue by vitalitasia** [Tensai75/NZBDonkey#1]
hello, im trying to download nzbs from "usnt-4all.**" nzb monkey links are not working and when I highlight Title, header and Password then click on get nzb file in context menu, i dont get any download

I have set it to download the nzb with a download propmt (save as), so no forward to an client or something

also no groups are set. addon version is 0.6.4 and chrome is on version 71.0.3578.98 (64bit)

any help would be appreciated

**Comment by Tensai75** [comment]
Newer versions of NZBDonkey do not work on u4a because of personal reasons. You can install v0.6.2 which will still work on all domains:

https://github.com/Tensai75/NZBDonkey/releases
