### ISSUE TITLE
Typos found

### ISSUE THREAD

**Issue by sonypsx** [Tensai75/NZBDonkey#1]
First of all - thanks for the great work!

I've found some Typos...
If you're in settings of the AddOn in FF the Tab Text reads: "NZBDoneky Settings"
If you're in the settings (FF) under "Category" the first options reads: "Do not unse categories"

The above typos were found in version 0.1.5 -> i was not able to download the 0.1.7 version at https://addons.mozilla.org/de/firefox/addon/nzbdonkey/

The "add to FireFox" Button there is directed to version 0.1.5

**Comment by Tensai75** [comment]
Fixed in v0.3.0
