### ISSUE TITLE
nzbking bad results

### ISSUE THREAD

**Issue by snappy-1** [Tensai75/NZBDonkey#13]
Looks like the top match from nzbking was a partial match of a nzb inside a zip that included 29000 nzbs, all of which sabnzbd helpfully loaded. Putting double-quotes around nzbking searches may force more accuracy.

**Comment by Tensai75** [comment]
Thanks for opening this issue and updating your rating in the mozilla store.
Can you please tell me which header you were searching for which then resulted in this false hit?
I will certainly look into this and try to improve the accuracy.

**Comment by snappy-1** [comment]
very nsfw... u4a-lady.dee.dp.720p

**Comment by Tensai75** [comment]
Thanks.

Yeah, putting it into double-quotes resolves the issue in this case. I will probably update the search URL for NZBKing and place double-quotes around the search term in a next update.
Meanwhile you can actually change it for yourself.

In the NZBDonkey settings go to "NZB Search Engines" and deactivate NZBKing in the "Default Search Engines".
Then add and activate a "Custom Search Engine" with the following settings:

**Search Engine Name:** `NZBKing with double-quotes` (or any other name you want to give it)
**Search URL:** `https://nzbking.com/?q="%s"` (note the double-quotes arround the %s) 
**Response Type:** `HTML`
**JSON object path / Regex expression:** `href="\/nzb:(.*?)\/"`
**Group no.:** `1`
**Download URL:** `https://nzbking.com/nzb:%s/`

![image](https://user-images.githubusercontent.com/34959627/104687855-4853cc80-5700-11eb-9879-54b5c31afb46.png)

Now NZBDonkey will search NZBKing with double-quotes arround the search term.
Hope this helps.

Regards, Tensai

**Comment by snappy-1** [comment]
thanks, Custom Search Engine worked great
