### ISSUE TITLE
Funktioniert nicht mit langen NZBInk

### ISSUE THREAD

**Issue by Soremta** [Tensai75/NZBDonkey#16]
Leider funktioniert der Donkey nicht mit allen NZBInk's. Z.b [nzblnk:?t=Standoff%202016%20German%20AC3%20WEBRiP%20x264-MULTiPLEX&h=3Ux2PVo_dPMc2zmXWJ&p=oo@ZfjoLo@Ffnni](url)
Funktioniert aber ohne probleme mit dem Monkey. Kann dies behoben werden?

*edit* liegt wohl am sonderzeichen im Passwort :(

**Comment by Tensai75** [comment]
Dieser NZBlnk wurde nicht korrekt erstellt bzw. urlcodiert. Der Passwort-Parameter enthält Sonderzeichen (@) welche in einer URL nicht erlaub sind. Korrekt wäre der NZBlnk Link so:
nzblnk:?t=Standoff%202016%20German%20AC3%20WEBRiP%20x264-MULTiPLEX&h=3Ux2PVo_dPMc2zmXWJ&p=ooZf%40jo%40LoFfnni
Da es sich hier also um einen Fehler beim Erstellen des NZBlnk handelt, kann ich nichts machen.
