### ISSUE TITLE
HouseOfUsenet problem

### ISSUE THREAD

**Issue by wetanni** [Tensai75/NZBDonkey#17]
Since few days intercepting from HoU fails: Error: the server responded with error code 403 (Forbidden)

Title: Mission Impossible Phantom Protokoll 2011 German DL 2160p UHD BluRay x265-ENDSTATiON
Header: undefined
Password: undefined

Happens on all on HoU

Can you confirm this?

**Comment by Tensai75** [comment]
Yes, interception of NZB downloads by NZBDonkey on HoU unfortunately is no longer possible and fails with a 403 error (access forbidden).
This is due to additional security features which have been implemented by HoU and which cannot be overcome by NZBDonkey.

**Comment by wetanni** [comment]
ok, thanks. i'll try to talk to HoU, perhaps they can make it work again :)
