### ISSUE TITLE
No message to synology disk since update 7.5

### ISSUE THREAD

**Issue by Jonny1957** [Tensai75/NZBDonkey#18]
First of all, thank you very much for the tool!
Since version 7.5, sending to Diststation no longer works.
I installed version 7.4 manually, everything ok
Synology DS216  DSM 6.2.4-25556

**Comment by Tensai75** [comment]
Should be fixed with latest version. Sending the NZB file to Synology DownloadStation was successfully tested with DMS v7.1.1, v6.2 and v5.2.
