### ISSUE TITLE
NZBDonkey doesn't appear in context menu

### ISSUE THREAD

**Issue by greenbriel** [Tensai75/NZBDonkey#19]
Great extension, thanks so much! I have it installed in Firefox, I see it in the toolbar, I can get to settings etc., but it doesn't appear in the context-sensitive menu when I right click. Works as expected in Chrome, but I hate using Chrome. I looked at resolved issues and saw that another user fixed a Firefox issue by reinstalling Firefox, but no dice for me. Any ideas? Thanks again!

**Comment by JasperAlgra** [comment]
I have the same sometimes. Worked for months now, but not today. 
Unable to figure out why exactly.

**Comment by fidesachates** [comment]
Same thing for me. Suddenly stopped working

Edit: Chrome had an update and it worked after I restarted Chrome and applied the update.

**Comment by Tensai75** [comment]
Deinstalling and reinstalling the extension usually fixes such errors.
