### ISSUE TITLE
Only partially working on Vivaldi browser

### ISSUE THREAD

**Issue by twistyxxx** [Tensai75/NZBDonkey#20]
Hi,
since few days, nzbdonkey not working on some sites i use: house-of-usenet.com brothers-of-usenet.com my browser (vivaldi) just downloads the nzb to the download folder, while on drunkenslug, it works as expected -> let me choose category and the sends to sabnzbd.
Strange thing is, it works fine on firefox.
What could be the reason for struggling with vivaldi, it worked few days ago fine. Some setting? did i miss anything? PLease help!

**Comment by Tensai75** [comment]
Vivaldi is not supported. Testing is only done with FF and Chrome.
