### ISSUE TITLE
What is the Correct Custom Search String for easynews.com

### ISSUE THREAD

**Issue by togotom** [Tensai75/NZBDonkey#24]
I have already tried several variants but do not reach the goal, every time I start a search with the right mouse button #GET NZB File# NZBdonkey glows red.
Here is my search string:
**Active Search Engine Name**
EasyNews
**Search URL**
https://members.easynews.com/2.0/index/advanced?=-&gps=%s
**Response Type**
HTML
**JSON object path**
name="(\d{9,})"
**Regex expression Group no.**
1
**Download URL**
https://members.easynews.com/dl/auto/443/nzb:%s/

Where do I make the mistake ?

**Comment by Tensai75** [comment]
Unfortunately, including the easynews search as a custom search engine is not possible.
Easynews doesn't group all the individual files of one upload into one search result (like the other indexers) but shows them individually. And therefore it would require some additional code specific for easynews to handle these search results and to download a combined NZB of all the required files.
