### ISSUE TITLE
Connecting SAB - Error code 0

### ISSUE THREAD

**Issue by televisi** [Tensai75/NZBDonkey#25]
Hello,
Thanks for providing such a good Chrome add-on.

I tried to connect NZBDonkey 0.7.5 (beta) to SAB 3.7.1; but it keeps throwing the following error:
```
Error: An error occurred while connection to SABnzbd
Error: the server responded with error code 0

```
The thing is, when I test the connection, SAB received the connection; although the API seems not included on the payload.
Error received on SAB:

```
API key missing, please enter the API key from Config->General into your 3rd party program: ::ffff:192.168.1.166 [Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36]
```

I have tried to include either the API OR NZB key, but the error persists; am I missing something here?
https://imgur.com/a/GyhdfvO
Thanks

**Comment by Tensai75** [comment]
Should be fixed with newest version.
