### ISSUE TITLE
This donkey doesn't want to work!

### ISSUE THREAD

**Issue by ratter99** [Tensai75/NZBDonkey#26]
I'm a noob, I have to be honest stuff like this is out of my pay grade but I love the idea of this extension but can't get it working.
I've Firefox on a MacBook Pro, my Sabnzbd is in a docker on a Qnap.
Everything in donkey is default except sending files to sab, donkey tells me sab is connected ok, I right click on a link and nothing happens, not sure where the file goes but not to sab and donkey knows nothing.
I don't fully understand any of the settings so I'm reluctant to alter,
And help here would be very much appreciated

**Comment by Tensai75** [comment]
Please ask this question in your preferred Usenet forum where NZBLNK is used. There are certainly experienced users there who know how to set up NZBDonkey.
This is not the right place for user support.
