### ISSUE TITLE
issue with nzb download intercept

### ISSUE THREAD

**Issue by lockevod** [Tensai75/NZBDonkey#29]
Hello, i'm triying to use the intercept option but it's not working with useneth.li

Source code in page is something like

a class="ipsAttachLink ipsAttachLink_block" data-fileid="53275" href="https://www.usenethd.li/applications/core/interface/file/attachment.php?id=IDNUMBER&amp;key=xxxxxxxxxxxx" data-fileext="nzb" rel="" data-loaded="true">  <span class="ipsAttachLink_title">Quien es a 1 (NF) NZB identifier}}.nzb</span><span class="ipsAttachLink_metaInfo">  <span class="ipsFlex-inline ipsFlex-ai:center ipsFlex-jc:center"><span>2.1 MB</span><span>&nbsp;·&nbsp;</span><span>2 descargas</span></span> </span> </a

Could you help me? I've configured like post request and usenethd.li (domain)

Thanks

**Comment by Tensai75** [comment]
Don't have access to usenethd.li so can't help.
