### ISSUE TITLE
Feature Request: Intercept NZB-file downloads

### ISSUE THREAD

**Issue by ChaosMarc** [Tensai75/NZBDonkey#4]
It would be great if additional to intercepting nzblnk-urls NZBDonkey would intercept NZB-file downloads and send them automatically to your configured downloader (which could be the actual download). this way there is no need for other browser extensions like SabConnect++ or NZB Unity

PS: great tool. I love it!

**Comment by Tensai75** [comment]
Intercepting a nzb file download can easily be done as long as the request url directly points to the nzb file and includes the nzb file name with the .nzb extension. However, this is often not the case. Therefore intercepting just links to nzb files would not cover most of the nzb file download requests.
In my opinion, such a feature would hence require to sniff into every request's response header to check whether maybe a nzb file is served. I don't know if this can be done at all and how it might impact the browser's performance. But I will think about it how this can be achieved.

**Comment by ChaosMarc** [comment]
Alternatively you could enable it only on the usual websites (and let the user manually add custom sites). I think this is the way extensions like SabConnect++ or NZB Unity display their additional download button.

**Comment by Tensai75** [comment]
I already have a test version working, which intercepts nzb downloads based on the response headers. It is working quite well on most sites I have tried it. Only binsearch.info is causing me some troubles. But I believe I will be able to tackle this down eventually.

**Comment by Tensai75** [comment]
Implemented with commit a8032a5904c57f07fe8964df0ccb6d349e74e107 (v0.5.0).
