### ISSUE TITLE
Filename from tab-name - enhancement

### ISSUE THREAD

**Issue by wetanni** [Tensai75/NZBDonkey#8]
If I may, I would propose an ehancement for this great addon. Can you add an option to get the name of the nzb being saved to disk from the tabname? I mainly use it on kleverig and there info looks like that:

> Poster: OwN-Upload
> Post Date: 11.06.2020
> Group: alt.binaries.nzb
> File: 1KZ9x1bs7Nz6v6beMkWds3J83N
> Pass: blablabla
> Release Date: 11.06.2020

as you see the file name is cryptic, but the real name of the movie is in the tab/window name. atm i use a addiotional tool to get the tabname and manually enter it in nzbdonkey, but i guess this can be automated?

**Comment by Tensai75** [comment]
Such an option would certainly be possible but are you really sure that the name/title isn't displayed somewhere within the tab/window but only as the tab/window name? Sounds pretty strange to me. Kleverig is a forum, isn't it? And although I have no account for kleverig I know a lot of such usenet boards and I would strongly expect the name/title to be stated somewhere in the displayed forum post.

Maybe you just don't know of the feature that NZBDonkey does use the first selected line as the name/title by default if no other name/title information was found. So all you have to do is select all the text, starting from the title/name as the first line of the selection down to the "file:" and "pass:" information. You can select a pretty huge amount of text and this should still work.

**Comment by wetanni** [comment]
That was the clue, didn't know that. Thanks a lot for giving me advice
